//
// Created by federico on 27/02/2021.
//

#ifndef DISTRIBUTED_SYSTEM_SIMULATOR_SRC_BEHAVIOURS_NODES_BEHAVIOUR_H_
#define DISTRIBUTED_SYSTEM_SIMULATOR_SRC_BEHAVIOURS_NODES_BEHAVIOUR_H_

class NodesBehaviour {};

#endif //DISTRIBUTED_SYSTEM_SIMULATOR_SRC_BEHAVIOURS_NODES_BEHAVIOUR_H_
